name: Install
on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Instalação FFMPEG
      run: |
        sudo apt update --y
        sudo apt install ffmpeg --y
    - name: Executar FFMPEG
      run:
        ffmpeg --help
    - name: Verificar versão do ffmpeg
      run: ffmpeg -version
